spring:
  security:
    oauth2:
      client:
        registration:
          service-2:
            client-id: service-2
            client-secret: service2
            authorization-grant-type: client_credentials
            scope: service1.read
            client-name: spring-client
        provider:
          service-2:
            token-uri: http://localhost:8082/oauth2/token